version: "3"

services:
  api:
    build: api/
    network_mode: host
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - SSL_CRT_FILE=${SSL_CRT_FILE}
      - SSL_KEY_FILE=${SSL_KEY_FILE}
    read_only: true
    tmpfs:
    - /app/submissions
    - /tmp

  react-frontend:
    build: react-frontend/
    network_mode: host
    environment:
      - HTTPS=${HTTPS}
      - SSL_CRT_FILE=${SSL_CRT_FILE}
      - SSL_KEY_FILE=${SSL_KEY_FILE}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
      - DISABLE_ESLINT_PLUGIN=true
    read_only: true
    tmpfs:
    - /tmp
    - /root/.npm